/**
 * Options for {@link generateIndex}.
 */
export interface GenerateIndexOptions {
	/**
	 * Module specifier the generated file imports `render` from.
	 * Defaults to `'svelte-email-kit'`.
	 */
	importSource?: string;
}

/** Header comment marking the generated file as machine-written. */
const HEADER = '// AUTO-GENERATED by svelte-email-kit/vite — do not edit.';

/**
 * Split a basename (sans `.svelte`) into word tokens.
 *
 * Boundaries are any run of non-alphanumeric characters (`-`, `_`, spaces, …)
 * **and** lower→upper transitions, so `order-receipt`, `order_receipt`, and
 * `OrderReceipt` all tokenize to `['order', 'receipt']`. Leading digits inside a
 * token are kept; empty tokens are dropped.
 */
function tokenize(stem: string): string[] {
	return stem
		.replace(/([a-z0-9])([A-Z])/g, '$1 $2')
		.split(/[^A-Za-z0-9]+/)
		.filter(Boolean);
}

/** `['order','receipt']` → `'orderReceipt'`. */
function toCamelCase(tokens: string[]): string {
	return tokens
		.map((tok, i) => {
			const lower = tok.toLowerCase();
			if (i === 0) return lower;
			return lower.charAt(0).toUpperCase() + lower.slice(1);
		})
		.join('');
}

/** `['order','receipt']` → `'OrderReceipt'`. */
function toPascalCase(tokens: string[]): string {
	return tokens
		.map((tok) => {
			const lower = tok.toLowerCase();
			return lower.charAt(0).toUpperCase() + lower.slice(1);
		})
		.join('');
}

/**
 * Ensure an identifier is a valid JS identifier: prefix a `_` if it starts with
 * a digit, and fall back to `Email`/`email` when tokenization produced nothing.
 */
function safeIdentifier(name: string, fallback: string): string {
	if (name === '') name = fallback;
	if (/^[0-9]/.test(name)) name = `_${name}`;
	return name;
}

/** A single email at a leaf of the registry tree. */
interface Leaf {
	/** Original `.svelte` file stem, the basis for the (per-folder) registry key. */
	stem: string;
	/** PascalCase import identifier (globally unique across the file). */
	ident: string;
	/** Relative import path from the registry file, e.g. `./auth/reset.svelte`. */
	importPath: string;
}

/** A folder in the registry tree: sub-folders (by raw name) plus its own emails. */
interface TreeNode {
	folders: Map<string, TreeNode>;
	leaves: Leaf[];
}

const newNode = (): TreeNode => ({ folders: new Map(), leaves: [] });

/**
 * Serialize a tree node to a (nested) object literal. Keys are camel-cased and
 * de-duplicated **per folder level** (sub-folders and emails share a namespace);
 * children are assigned keys in raw-name order (deterministic suffixing) and
 * emitted in key order.
 */
function serializeNode(node: TreeNode, depth: number): string {
	const indent = '\t'.repeat(depth);
	const closeIndent = '\t'.repeat(depth - 1);

	type Child =
		| { rawName: string; key: string; kind: 'folder'; node: TreeNode }
		| { rawName: string; key: string; kind: 'leaf'; leaf: Leaf };

	type RawChild =
		| { rawName: string; kind: 'folder'; node: TreeNode }
		| { rawName: string; kind: 'leaf'; leaf: Leaf };

	const raw: RawChild[] = [
		...[...node.folders].map(
			([rawName, child]): RawChild => ({ rawName, kind: 'folder', node: child })
		),
		...node.leaves.map((leaf): RawChild => ({ rawName: leaf.stem, kind: 'leaf', leaf }))
	];
	// Assign keys in raw-name order so suffixes are deterministic…
	raw.sort((a, b) => (a.rawName < b.rawName ? -1 : a.rawName > b.rawName ? 1 : 0));
	const used = new Set<string>();
	const children: Child[] = raw.map((child) => {
		const base = safeIdentifier(toCamelCase(tokenize(child.rawName)), 'email');
		let key = base;
		let suffix = 2;
		while (used.has(key)) key = `${base}${suffix++}`;
		used.add(key);
		return child.kind === 'folder'
			? { rawName: child.rawName, key, kind: 'folder', node: child.node }
			: { rawName: child.rawName, key, kind: 'leaf', leaf: child.leaf };
	});
	if (children.length === 0) return '{}';
	// …then emit in key order for a stable, readable file.
	children.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));

	const body = children.map((child, i) => {
		const comma = i === children.length - 1 ? '' : ',';
		const value =
			child.kind === 'folder'
				? serializeNode(child.node, depth + 1)
				: `(props: ComponentProps<typeof ${child.leaf.ident}>) => render(${child.leaf.ident}, props)`;
		return `${indent}${child.key}: ${value}${comma}`;
	});
	return `{\n${body.join('\n')}\n${closeIndent}}`;
}

/**
 * Build the typed registry source from a list of `.svelte` paths **relative to the
 * emails dir** — nested paths (`auth/password/reset-password.svelte`) are mirrored
 * into nested objects, so `emails.auth.password.resetPassword(props)`.
 *
 * Each path yields a camelCase key (`reset-password.svelte` → `resetPassword`),
 * de-duplicated within its folder, and a globally-unique PascalCase import
 * identifier. Each leaf returns `Promise<[html, text]>`, matching `render()`.
 *
 * An empty input still yields a valid file with `export const emails = {};`.
 */
export function generateIndex(sveltePaths: string[], options?: GenerateIndexOptions): string {
	const importSource = options?.importSource ?? 'svelte-email-kit';

	// Normalize separators, keep `.svelte` only, sort for deterministic ident suffixes.
	const paths = sveltePaths
		.map((p) => p.split(/[\\/]/).join('/'))
		.filter((p) => p.endsWith('.svelte'))
		.sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));

	const root = newNode();
	const usedIdents = new Set<string>();
	const allLeaves: Leaf[] = [];

	for (const filePath of paths) {
		const segments = filePath.split('/');
		const fileName = segments.pop()!;
		let node = root;
		for (const segment of segments) {
			let child = node.folders.get(segment);
			if (!child) {
				child = newNode();
				node.folders.set(segment, child);
			}
			node = child;
		}

		const stem = fileName.slice(0, -'.svelte'.length);
		const baseIdent = safeIdentifier(toPascalCase(tokenize(stem)), 'Email');
		let ident = baseIdent;
		let suffix = 2;
		while (usedIdents.has(ident)) ident = `${baseIdent}${suffix++}`;
		usedIdents.add(ident);

		const leaf: Leaf = { stem, ident, importPath: `./${filePath}` };
		node.leaves.push(leaf);
		allLeaves.push(leaf);
	}

	const lines: string[] = [HEADER];

	if (allLeaves.length === 0) {
		lines.push(`import type { ComponentProps } from 'svelte';`);
		lines.push('');
		lines.push('export const emails = {};');
		lines.push('export type Emails = typeof emails;');
		return lines.join('\n') + '\n';
	}

	lines.push(`import { render } from '${importSource}';`);
	lines.push(`import type { ComponentProps } from 'svelte';`);
	for (const { ident, importPath } of [...allLeaves].sort((a, b) =>
		a.importPath < b.importPath ? -1 : 1
	)) {
		lines.push(`import ${ident} from '${importPath}';`);
	}
	lines.push('');
	lines.push(`export const emails = ${serializeNode(root, 1)};`);
	lines.push('export type Emails = typeof emails;');

	return lines.join('\n') + '\n';
}
