import { describe, it, expect } from 'vitest';
import { generateIndex } from './generate-index.js';

describe('generateIndex', () => {
	it('emits imports, a typed registry, and the auto-generated header', () => {
		const out = generateIndex(['WelcomeEmail.svelte', 'order-receipt.svelte']);

		expect(out).toContain('// AUTO-GENERATED by svelte-email-kit/vite — do not edit.');
		expect(out).toContain(`import { render } from 'svelte-email-kit';`);
		expect(out).toContain(`import type { ComponentProps } from 'svelte';`);
		expect(out).toContain(`import WelcomeEmail from './WelcomeEmail.svelte';`);
		expect(out).toContain(`import OrderReceipt from './order-receipt.svelte';`);
		expect(out).toContain(
			`welcomeEmail: (props: ComponentProps<typeof WelcomeEmail>) => render(WelcomeEmail, props)`
		);
		expect(out).toContain(
			`orderReceipt: (props: ComponentProps<typeof OrderReceipt>) => render(OrderReceipt, props)`
		);
		expect(out).toContain('export type Emails = typeof emails;');
	});

	it('camelCases snake_case and PascalCase file names consistently', () => {
		const out = generateIndex(['welcome_email.svelte', 'OtpEmail.svelte']);
		expect(out).toContain(`welcomeEmail: (props: ComponentProps<typeof WelcomeEmail>)`);
		expect(out).toContain(`import WelcomeEmail from './welcome_email.svelte';`);
		expect(out).toContain(`otpEmail: (props: ComponentProps<typeof OtpEmail>)`);
		expect(out).toContain(`import OtpEmail from './OtpEmail.svelte';`);
	});

	it('emits a valid minimal file for an empty list', () => {
		const out = generateIndex([]);
		expect(out).toContain('// AUTO-GENERATED by svelte-email-kit/vite — do not edit.');
		expect(out).toContain('export const emails = {};');
		expect(out).toContain('export type Emails = typeof emails;');
		// No render import / default imports when there are no entries.
		expect(out).not.toContain(`from 'svelte-email-kit'`);
		expect(out).not.toContain('=> render(');
	});

	it('ignores non-.svelte entries', () => {
		const out = generateIndex(['welcome.svelte', 'index.ts', 'README.md']);
		expect(out).toContain(`import Welcome from './welcome.svelte';`);
		expect(out).not.toContain('index.ts');
		expect(out).not.toContain('README');
	});

	it('de-dupes colliding keys/identifiers deterministically', () => {
		const out = generateIndex(['welcome.svelte', 'Welcome.svelte']);
		// Both collide on `welcome`/`Welcome`; the second (sorted) gets a `2` suffix.
		expect(out).toContain(`import Welcome from './Welcome.svelte';`);
		expect(out).toContain(`import Welcome2 from './welcome.svelte';`);
		expect(out).toContain(`welcome: (props: ComponentProps<typeof Welcome>)`);
		expect(out).toContain(`welcome2: (props: ComponentProps<typeof Welcome2>)`);
		// Deterministic across runs.
		expect(generateIndex(['welcome.svelte', 'Welcome.svelte'])).toBe(out);
	});

	it('sorts entries by key for stable output', () => {
		const out = generateIndex(['zebra.svelte', 'apple.svelte']);
		expect(out.indexOf('apple:')).toBeLessThan(out.indexOf('zebra:'));
	});

	it('respects the importSource override', () => {
		const out = generateIndex(['welcome.svelte'], { importSource: '$lib/index.js' });
		expect(out).toContain(`import { render } from '$lib/index.js';`);
		expect(out).not.toContain(`from 'svelte-email-kit'`);
	});

	it('mirrors nested folders into nested objects', () => {
		const out = generateIndex([
			'auth/password/reset-password.svelte',
			'auth/password/password-change.svelte',
			'welcome.svelte'
		]);
		// Imports use the nested relative path.
		expect(out).toContain(`import ResetPassword from './auth/password/reset-password.svelte';`);
		expect(out).toContain(`import PasswordChange from './auth/password/password-change.svelte';`);
		expect(out).toContain(`import Welcome from './welcome.svelte';`);
		// Nested object shape: emails.auth.password.{resetPassword,passwordChange}.
		expect(out).toContain('auth: {');
		expect(out).toContain('password: {');
		expect(out).toContain(
			`resetPassword: (props: ComponentProps<typeof ResetPassword>) => render(ResetPassword, props)`
		);
		expect(out).toContain(
			`passwordChange: (props: ComponentProps<typeof PasswordChange>) => render(PasswordChange, props)`
		);
		// Top-level entry sits beside the folder.
		expect(out).toContain(
			`welcome: (props: ComponentProps<typeof Welcome>) => render(Welcome, props)`
		);
	});

	it('camelCases folder segments', () => {
		const out = generateIndex(['order-emails/shipped.svelte']);
		expect(out).toContain('orderEmails: {');
		expect(out).toContain(`shipped: (props: ComponentProps<typeof Shipped>)`);
		expect(out).toContain(`import Shipped from './order-emails/shipped.svelte';`);
	});

	it('keys the same file name in different folders independently (distinct idents)', () => {
		const out = generateIndex(['a/welcome.svelte', 'b/welcome.svelte']);
		expect(out).toContain(`import Welcome from './a/welcome.svelte';`);
		expect(out).toContain(`import Welcome2 from './b/welcome.svelte';`);
		expect(out).toContain('a: {');
		expect(out).toContain('b: {');
		// Same key `welcome` under each parent; different idents.
		expect(out).toContain(
			`welcome: (props: ComponentProps<typeof Welcome>) => render(Welcome, props)`
		);
		expect(out).toContain(
			`welcome: (props: ComponentProps<typeof Welcome2>) => render(Welcome2, props)`
		);
		// Deterministic.
		expect(generateIndex(['a/welcome.svelte', 'b/welcome.svelte'])).toBe(out);
	});

	it('normalizes backslash separators', () => {
		const out = generateIndex(['auth\\reset.svelte']);
		expect(out).toContain(`import Reset from './auth/reset.svelte';`);
		expect(out).toContain('auth: {');
	});
});
